services:
  test-github-backup:
    build: .
    container_name: test-github-backup
    volumes:
      - ./backups/:/backups/
    environment:
      - INSTANT_RUN=true
      - CRON=* * * * *
      - GITHUB_USERNAME=${GITHUB_REPOSITORY_USERNAME}
      - GITHUB_PASSWORD=${GITHUB_REPOSITORY_PASSWORD}
